# -*- coding: utf-8 -*-
"""SVC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9YZPIFJr5-WghbU-HDcSzqdihmobP2Q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

d=pd.read_csv("/content/survey lung cancer.csv")

d.isna()

d.isna().sum()

d

x=d.drop(["LUNG_CANCER"],axis=1)
y=d["LUNG_CANCER"]

from sklearn.preprocessing import LabelEncoder
le_gender = LabelEncoder()
x['GENDER'] = le_gender.fit_transform(x['GENDER'])

le_lung_cancer = LabelEncoder()
y = le_lung_cancer.fit_transform(y)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

from sklearn.svm import SVC

svc=SVC()
svc.fit(x_train,y_train)

y_pred=svc.predict(x_test)
print(y_pred)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))